apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentdtest
  namespace: kube-logging
  labels:
    app: fluentd2
spec:
  selector:
    matchLabels:
      app: fluentd2
  template:
    metadata:
      labels:
        app: fluentd2
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd2
        image: zedahmed144/s3-es:1.0 #image2 works only with es .. image 6 error with worng credentials
        env:
          - name: "S3_BUCKET_NAME"
            value: "efk-centos-22b"
          - name: "S3_BUCKET_REGION"
            value: "us-east-1"
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch.kube-logging.svc.cluster.local"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENTD_SYSTEMD_CONF
            value: disable
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
